//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }

  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func validate() throws {

  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.color` struct is generated, and contains static references to 6 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }

    /// Color `addTicketButton`.
    var addTicketButton: RswiftResources.ColorResource { .init(name: "addTicketButton", path: [], bundle: bundle) }

    /// Color `blue`.
    var blue: RswiftResources.ColorResource { .init(name: "blue", path: [], bundle: bundle) }

    /// Color `infoTextFieldFillColor`.
    var infoTextFieldFillColor: RswiftResources.ColorResource { .init(name: "infoTextFieldFillColor", path: [], bundle: bundle) }

    /// Color `navyBlue`.
    var navyBlue: RswiftResources.ColorResource { .init(name: "navyBlue", path: [], bundle: bundle) }

    /// Color `red`.
    var red: RswiftResources.ColorResource { .init(name: "red", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 3 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `coldPlay`.
    var coldPlay: RswiftResources.ImageResource { .init(name: "coldPlay", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `connect`.
    var connect: RswiftResources.ImageResource { .init(name: "connect", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `kevinHeart`.
    var kevinHeart: RswiftResources.ImageResource { .init(name: "kevinHeart", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.file` struct is generated, and contains static references to 1 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `GoogleService-Info.plist`.
    var googleServiceInfoPlist: RswiftResources.FileResource { .init(name: "GoogleService-Info", pathExtension: "plist", bundle: bundle, locale: LocaleReference.none) }
  }
}